version: '3.8'

services:
  sb5-docker-test:
    container_name: fastapi_service
    restart: always
    ports:
      - "8001:8001"
    environment:
      - ENV=production
      - TZ=America/New_York
    volumes:
      # Synology paths MUST start with /volumeX/
      - /volume1/docker/sb5-docker-test/logs:/app/logs
      - /volume1/docker/sb5-docker-test:/app/data
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge